### ISSUE TITLE
information request

### ISSUE THREAD

**Issue by Linoa235** [NightmareXIV/Splatoon#101]
Hi for the eureka trunk presets there is something in particular to do because I still haven't got the indications since the update ^^. if you have any solution

Thank you in advance for your answers !

**Comment by Limiana** [comment]
Hello! They should work after you imported them, please check if presets support your game's language... otherwise I'm afraid I can't help much as I currently don't do this content and have no way to verify or fix it

**Comment by Linoa235** [comment]
ah ok thank you i'm with the europe version that's why i imported tested but nothing indicated

**Comment by Limiana** [comment]
If you require further assistance, please reopen issue here: https://github.com/PunishXIV/Splatoon
