### ISSUE TITLE
feature: add option to zone lock elements

### ISSUE THREAD

**Issue by WulfRage** [NightmareXIV/Splatoon#11]
zone locking elements might be a nice feature to have? i was trying to set up a layout for fishing locations and created a element for the kholusian legendary fish which was fine, but when i went to the tempest to setup the marker for the legendary lancetfish i noticed that it was still placing the kholusia marker somewhere in tempest so i would need to make multiple zone locked layouts but i dont really want to have to make multiple layouts for each element that is in different zones so the option to zone lock each element would be nice for this. i know what i was trying to do is a bit extra and not needed but this might be nice in other situations too but i have no idea how hard it would be to add this while still allowing the ability to zone lock a whole layout.

**Comment by Eternita-S** [comment]
Hello!
That's what layouts are for, really, for creating sets of conditions basically. Elements aren't supposed to have individual properties, they are supposed to form a single uniform overlay. 
If you are concerned about grouping up - soon I'll be making a feature that allows you to group layouts up and manage the whole group at once - export, import, disable or enable, so go ahead and create layouts in meantime - there is no performance problem or anything else with that.
