### ISSUE TITLE
Feature request:Stroke & Fill & Transparency

### ISSUE THREAD

**Issue by CNLenoli** [NightmareXIV/Splatoon#37]
The display of the Splatoon waymaker is now somewhat blocked from the player's view. Hopefully the ability to customize the transparency of the warmaker's fill and stroke can be added, and they can all be edited individually. It would be nice to be able to change from one color to another over time to better demonstrate the AOE damage proc time.

**Comment by Eternita-S** [comment]
You should be able to edit transparency by clicking on color and editing "A" value:
![image](https://user-images.githubusercontent.com/5073202/167327179-f6513e78-a34b-4df4-835a-60853ab0c80e.png)

Can't edit fill and stroke separately (fill just removes stroke all together), it will be added in future. Though, you can bypass it for now: just create unfilled copy of element (though that is only for circles; for lines something good will come in near future).
