### ISSUE TITLE
Feature Request: OR-List or RegEx matching for Compare Attribute Name

### ISSUE THREAD

**Issue by Ranzlappen** [NightmareXIV/Splatoon#53]
Is it possible for the Textbox at "compare attribute" in an Element to have a list of items or Regex matching instead of just one item, wouldn't that cut down on resources opposed to creating alot of different elements?

**Comment by Eternita-S** [comment]
Performance wise it will be roughly same amount of comparisons (whether you scan object table X times to do 1 comparison each scan or do X comparisons for each object - it's roughly the same amount of work), however I will consider adding it for convenience, but it will be done at a later time (likely at gui rework time)
