### ISSUE TITLE
The Chinese client fails to load normally

### ISSUE THREAD

**Issue by luenlin** [NightmareXIV/Splatoon#65]
![image](https://user-images.githubusercontent.com/27433283/193424619-c9a75dd1-f275-4cda-9284-f6811f9df053.png)
UnbanPluginsCN already installed

**Comment by Limiana** [comment]
Hello!
Chinese client uses different versions of plugins. 
Please remove `https://raw.githubusercontent.com/NightmareXIV/MyDalamudPlugins/main/pluginmaster.json` from your custom repo list and add different link: `https://raw.githubusercontent.com/NightmareXIV/MyDalamudPlugins/main/cn.json`
