### ISSUE TITLE
Preset Related Question: 

### ISSUE THREAD

**Issue by SoraChan77** [NightmareXIV/Splatoon#69]
Hello there.

Currently i am working on some presets for A.S.S's last boss Shadowcaster.
But i am coming across an issue where i know that game already spawns the environment entities (Fireballs in this case) before they are visible to the player (I can confirm this with a tool like event trigger).

So my question is there a specific setting that i am missing where it would display the set marker as soon as the invisible entities spawn( while they are still invisible to the player)
Currently i have targeting setting on "any" and unticked the visible enemies only

The markers are drawn correctly as soon as the entities become visible to the player.

Thanks!

**Comment by Limiana** [comment]
Hello. Apologies for delay. These are likely map effects, for which you can create trigger or wait for upcoming scripting feature.
