### ISSUE TITLE
Layouts Search bar shrinking

### ISSUE THREAD

**Issue by zbee** [NightmareXIV/Splatoon#72]
![splatoon_shrink](https://user-images.githubusercontent.com/1582821/205456074-b37ff0af-ad83-4df4-aaba-66cbf72804bb.gif)

I don't really know what else to say, the bar just continually shrinks and expands back to full width.
The buttons and the search bar still work, but yeah ... just shrinks.

My screen is 3440x1440, I know at one point there was a plugin (PartyIcons, maybe?) and its window would continually widen and then reset and do it again; in the patch notes apparently it was related to the screen size somehow, so maybe that's a hint, unsure.

**Comment by Limiana** [comment]
I'm not sure what's going on here, but try version 3.0.0.3 - I made some changes that could fix this problem. If it doesn't helps, please upload `%appdata%\XIVLauncher\dalamudConfig.json` file for diagnostics.

**Comment by zbee** [comment]
It seems this was addressed in 3.0.0.3, yes.
