### ISSUE TITLE
Chinese fork of Dalamud currently failed to load

### ISSUE THREAD

**Issue by cerantes** [NightmareXIV/Splatoon#73]
SOS，Chinese fork of Dalamud currently failed to load （I have run the
UnbanPluginsCN）：

This plugin failed to load.Please contact the author for more information.

Help, I can't do without it :(((
If there is no way to solve it, thank you for bringing such a convenient plugin！
![QQ截图20221220001245](https://user-images.githubusercontent.com/94860263/208471718-fe9794a7-55dc-4beb-b0e1-b3e1928d4310.png)

**Comment by Limiana** [comment]
Hello!
Chinese client uses different versions of plugins. 
Please remove `https://raw.githubusercontent.com/NightmareXIV/MyDalamudPlugins/main/pluginmaster.json` from your custom repo list and add different link: `https://raw.githubusercontent.com/NightmareXIV/MyDalamudPlugins/main/cn.json`

**Comment by cerantes** [comment]
> 
solved! thank you very much!

**Comment by cerantes** [comment]
I'm so sorry, here I go again. Today, the CN server was updated to 6.2, Chinese fork of Dalamud currently prompted that Splatoon needs to be updated，Would you spare some time to update? thank you very much！

![QQ截图20221220001245](https://user-images.githubusercontent.com/94860263/208675600-e8176119-d903-4e68-818f-c60901ec18c9.png)

**Comment by Limiana** [comment]
It should be resolved now

**Comment by cerantes** [comment]
> 
yes!3Q,LOVE!
