### ISSUE TITLE
Preset: UCOB - Heavensfall Knockback Zone

### ISSUE THREAD

**Issue by DatGoose** [NightmareXIV/Splatoon#74]
Short description: After dodging the dives a ring will appear in the center, stand in the circle to reach the perfect knockback range without taking lethal damage from the heavensfall tower.

<~Lv2~{"Name":"Heavensfall Knockback","Group":"UCOB","ZoneLockH":[733],"DCond":5,"ElementsL":[{"Name":"","refX":0.013264656,"refY":-0.29209137,"radius":9.74,"Donut":0.99}],"UseTriggers":true,"Triggers":[{"Type":2,"Duration":11.0,"Match":"Bahamut Prime readies Heavensfall Trio","MatchDelay":13.0}]}>
```

```

**Comment by DatGoose** [comment]
The rings timing to disappear could be a bit more fine tuned but it will disappear shortly before the first pizza slice will explode. I'm done with this fight and wont be going back in until 6.5 so I wont have a chance to fine tune its timing.

**Comment by Limiana** [comment]
Thanks! Will add it shortly
