### ISSUE TITLE
feature request: add subcommand 'toggle' for layout

### ISSUE THREAD

**Issue by Elypha** [NightmareXIV/Splatoon#75]
Hello,

The problem is mainly about the following commands:
```
/splatoon enable <layout>
/splatoon disable <layout>
/splatoon enable <layout>~<element>
/splatoon disable <layout>~<element>
```
Could you please add a `/splatoon toggle <layout>` to switch between on and off?

**Comment by Limiana** [comment]
Hello, yes, I will add it in the next update
