### ISSUE TITLE
I cannot  import the "[Script] Limitless Desolation tower highlight"

### ISSUE THREAD

**Issue by cerantes** [NightmareXIV/Splatoon#76]
Dear Limiana：
I cannot  import the "[Script] Limitless Desolation tower highlight". After each import, it will only prompt that it is downloading, but nothing actually happens.Doesn't work whether running a VPN or not
(I use Chinese fork of Dalamud currently and JP fork can import.)
![QQ截图20230107142832](https://user-images.githubusercontent.com/94860263/211134680-da459d67-038d-42a2-93d4-a8832a8d1a79.png)
![QQ截图20230107142917](https://user-images.githubusercontent.com/94860263/211134682-1c95028d-8789-43a5-a93d-c9f15530e263.png)

**Comment by Limiana** [comment]
Hello. Can you send me your `dalamud.log` file after an attempt to import script? (import it, wait 5 minutes, then send log)

**Comment by QK777** [comment]
I have the same phenomenon.
[dalamud.zip](https://github.com/NightmareXIV/Splatoon/files/10426606/dalamud.zip)

**Comment by Limiana** [comment]
It looks like you're trying to import whole page or something like that
Use the copy button like here on screenshot:
![image](https://user-images.githubusercontent.com/5073202/212720659-ed14e5c2-5311-4804-9ebd-7b57cc4ce977.png)
And try importing after you clicked on it

**Comment by QK777** [comment]
Using that copy button was no good.
The [Script] one succeeded and the [international] one failed. Perhaps I am using it incorrectly?
I took a short video and will upload a new log as well.

https://www.youtube.com/watch?v=mXRoUZbaDA0
[dalamud.log](https://github.com/NightmareXIV/Splatoon/files/10428184/dalamud.log)

**Comment by Limiana** [comment]
Please import presets using "Layouts" tab. "Scripts" tab is only for scripts, that are labeled as [Script].
(Layouts tab can import both normal layouts and scripts by the way)

**Comment by QK777** [comment]
Thank you for responding to my question. It worked.

**Comment by cerantes** [comment]
> 你好。`dalamud.log`你能在尝试导入脚本后把你的文件发给我吗？（导入它，等待5分钟，然后发送日志）

I'm very sorry, I've been busy with work these days and forgot to check outlook! I'll try importing the script again tonight when I get home from get off work and send you log , thanks a lot!

**Comment by cerantes** [comment]
I usd "Layouts" tab,but nothing……
https://youtu.be/q1Uzw2N2KSE
[dalamud.log](https://github.com/NightmareXIV/Splatoon/files/10434839/dalamud.log)

**Comment by Limiana** [comment]
Hello, I'm sorry, but I will only be able to fix this issue at a later date. I'm having busy time right now.

**Comment by cerantes** [comment]
> 

It doesn't matter. Although I don't understand the problem, I solved it by copying and pasting my friend's folder!
Thank you again!

**Comment by Limiana** [comment]
If you require further assistance, please reopen issue here: https://github.com/PunishXIV/Splatoon
