### ISSUE TITLE
Striking Dummy centered around top rather than base on zone load

### ISSUE THREAD

**Issue by diwo** [NightmareXIV/Splatoon#77]
Striking dummies that already have been placed at the time you enter a zone have their position centered around the top of the dummy rather than the bottom. This causes elements drawn relative to the dummy to be elevated above the ground. For example melee rings would float in midair rather than being drawn on the ground.

Repro steps:
1. Enter an outdoor housing area
2. Place an "Oriental Striking Dummy" outdoor furnishing (was able to repro with another dummy type)
3. Enter estate interior, and exit estate back outside
4. `/sf dummy`, ring appears on top of dummy instead of on the ground
5. Use housing menu to reposition dummy while `/sf` is still on, ring now appears on the ground

**Comment by Limiana** [comment]
Hello!
Striking dummies that are placed in the world may report their location incorrectly - this is an in-game bug. Additionally, they report incorrect hitbox radius.
If you would like to test a preset on a striking dummy, please start any duty in explorer mode and spawn a dummy there - they will be accurate.
