### ISSUE TITLE
Feature Request: Could u add another Static position strat?

### ISSUE THREAD

**Issue by Redmoonwow** [NightmareXIV/Splatoon#80]
Dear: Limiana
splatoon is very helpful. thank you.
This is the main subject, but if you don't mind, could you add the tactics that culul is doing?

Mid
〇　　〇
×　　  ×
△　　△
□　　  □

Far
□ 　　〇
×　　  ×
△　　△
〇　 　□

For "Far", ×△ is almost the same as "mid" tactics. Extend it to the outer circumference as it is without crossing it.
Place SS (right Pattern) on it.
I should make my own, but I'm still learning. I'm sorry. 

@ Google Translate speaker

![image](https://user-images.githubusercontent.com/50778349/215367641-07b58a47-bb44-4ee1-b647-5fed6eb8c41d.png)
![{8E62B66B-9E19-4794-B214-C512DA139100}](https://user-images.githubusercontent.com/50778349/215367667-e8a8aa1b-f59a-408b-9b4e-7b05f7224ad9.png)

**Comment by Limiana** [comment]
Hello. I've added it, however, it will work only in English version of the game client.
I need these lines from Japanese client to make it work.
`You suffer the effect of Remote Glitch.`
`You suffer the effect of Mid Glitch.`
If you can, please send them. They can be found in Splatoon's log, or in ACT's logs.

**Comment by Redmoonwow** [comment]
Dear: Limiana
As a side note, the Japanese client doesn't seem to replace "You".
LEFT JP  RIGHT EN
![{03915042-A367-4594-93A1-3629CC008832}](https://user-images.githubusercontent.com/50778349/215638728-f023bcc6-6dea-4f8a-9d71-dbd5a7d81386.png)

**Comment by Limiana** [comment]
> If the head split is on one side, the head split farthest from the optical unit will adjust.
Work in progress on that
> As a side note, the Japanese client doesn't seem to replace "You".
It's good enough, thanks

**Comment by Limiana** [comment]
I have added JP language support into presets, please test it

**Comment by Redmoonwow** [comment]
In the commit of "4e25527613bba858176eca2a52f0346fab97ac1b", the following operation was confirmed and it worked normally.
・Culul's strat
・KB spots far
・KB spots close

It was very convenient. Thank you very much.
Please let me close this.
If you need JP client logs, please let me know.
