### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Linoa235** [NightmareXIV/Splatoon#83]
Hi, here I am new, I wanted to know if there is something to do so that the superimposed drawings can be activated at the right time and not all of the start of the fight. THANKS

I had not paid attention in savage it's good; I had tried only in zodiark suddenly no problem closed thank you ^^

**Comment by Limiana** [comment]
Hello, sorry, I haven't noticed the issue earlier. You can use triggers to delay drawings display

**Comment by Linoa235** [comment]
no worries, I made it. Thanks for answering anyway ^^
